### ISSUE TITLE
mention how to install pre-req's and libs in README.md

### ISSUE THREAD

**Issue by SvenDowideit** [accelerando-consulting/stacx#1]
ooo, look, a `make libs` - but it fails looksin for arduino-cli

**Comment by SvenDowideit** [comment]
actually, funny thing is - I failed to see the docs saying that `make libs` etc are a thing

I'll make a PR later

**Comment by SvenDowideit** [comment]
https://github.com/arduino/arduino-cli#get-the-latest-package ?

**Comment by SvenDowideit** [comment]
wow, funny, so to build the example, you need not just `make libs`, but also `make extralibs` ?

**Comment by unixbigot** [comment]
you want 'make installdeps' to install arduino cli, cores libs and extralibs.

I've updated the readme to explain this.   Also have a full docker build process about to push which solves the 'all arduino libraries are global' hell.

**Comment by unixbigot** [comment]
@SvenDowideit Please try the changes in commit 05d24b1b567ca34472cf9ac93bf484b3f0b8f958

**Comment by unixbigot** [comment]
Makefile has been further updated with some scripts that handle installation of build dependencies on windows and linux.

**Comment by unixbigot** [comment]
Readme updated to explain how to use the tool install scripts (or if not, how to use them as a guide to gui operations
