### ISSUE TITLE
ArduinoJson seems to require v6

### ISSUE THREAD

**Issue by SvenDowideit** [accelerando-consulting/stacx#3]
but for something else i was working on, I had v5 installed

which is a sad-surprise :)

**Comment by SvenDowideit** [comment]
mmm, installing v6.11.3, and the builds also fail.

**Comment by SvenDowideit** [comment]
also fails on 6.9.1

**Comment by unixbigot** [comment]
Arduino JSON has been, sorry to say, a shitshow.   Breaking changes not just from v5 to v6 but all through the v6 point releases have been a constant pain.   I'm using 6.11.0.

**Comment by unixbigot** [comment]
You'll like the dockerised build to compartmentalise dependencies.

**Comment by unixbigot** [comment]
Looks like I can pin the ArduinoJSON library version in the makefile.  whee!

`arduino-cli lib install ArduinoJSON@6.11.0`

**Comment by unixbigot** [comment]
@SvenDowideit Commit 05d24b1b567ca34472cf9ac93bf484b3f0b8f958 pins ArduinoJson and also provides a dockerised build mechanism for dependency containment.   Let me know if it works for you.

**Comment by SvenDowideit** [comment]
new error:
```
/home/sven/src/follyengine/stacx/stacx.ino:32:23: fatal error: SimpleMap.h: No such file or directory
 #include <SimpleMap.h>
                       ^
```

**Comment by SvenDowideit** [comment]
installed https://github.com/spacehuhn/SimpleMap and it compiles

**Comment by SvenDowideit** [comment]
oh lol!

```
sven@yoga260:~/src/follyengine/stacx$ make upload PORT=/dev/ttyUSB1
ls: cannot access '/home/sven/.arduino15/packages/esp32/hardware/esp32/': No such file or directory
python /home/sven/.arduino15/packages/esp32/hardware/esp32//tools/esptool.py --port /dev/ttyUSB1 write_flash 0x10000 stacx.ino.bin
python: can't open file '/home/sven/.arduino15/packages/esp32/hardware/esp32//tools/esptool.py': [Errno 2] No such file or directory
```

**Comment by SvenDowideit** [comment]
mmm, interesting - 

```
sven@yoga260:~/src/follyengine/stacx$ pip install esptool
Requirement already satisfied: esptool in /usr/local/lib/python2.7/dist-packages (2.5.0)
Requirement already satisfied: ecdsa in /usr/local/lib/python2.7/dist-packages (from esptool) (0.13)
Requirement already satisfied: pyaes in /usr/local/lib/python2.7/dist-packages (from esptool) (1.6.1)
Requirement already satisfied: pyserial>=3.0 in /home/sven/.local/lib/python2.7/site-packages (from esptool) (3.4)
```

and 

```
sven@yoga260:~/src/follyengine/stacx$ which esptool.py 
/usr/local/bin/esptool.py
```

**Comment by unixbigot** [comment]
Are you using ESP32 or ESP8266 -- path to esptool is set in the Makefile in the first few lines.   If you have esptool installed already in your path, just set ESPTOOL=esptool

Simplemap is listed in extralibs, (since a few commits back). You may need to run 'make extralibs' again.

**Comment by unixbigot** [comment]
try
```
make upload PORT=/dev/ttyUSB1 ESPTOOL=esptool.py
```

**Comment by SvenDowideit** [comment]
sadly, no, needs to be `make upload PORT=/dev/ttyUSB0 ESPTOOL=/usr/local/bin/esptool.py`

I guess one big question is - do you have a really really important reason to make installation complicated by having an "extralibs" that needs to be used to make your introductory example work?

and argh. flashing fails more than it succeeds.

**Comment by unixbigot** [comment]
Extralibs is there because of using AsyncTCP and AsyncMQTT.    Using the built in single-threaded TCP libraries hangs the whole sketch if the MQTT server is not reachable.

What device are you flashing?   Does it flash OK from the Arduino IDE?   There are some popular ESP32 dev boards that have a known design flaw in their flash circuit that can be fixed by adding a part.

**Comment by unixbigot** [comment]
@SvenDowideit I saw you had esptool2.5 in one of your pastes.   Try update.

**Comment by unixbigot** [comment]
There's been no recurrence of arduinojson heck.
